Algoritmo "exercicio2"

Var
   nomes: vetor[1..5] de caracter
   contador: inteiro


Inicio
   para contador de 1 ate 5 faca
      escreval("Digite o nome de numero ", contador,": ")
      leia(nomes[contador])
   fimpara

   escreval("")

   para contador de 1 ate 5 faca
      escreval(nomes[contador])
   fimpara

   escreval("")

   para contador de 5 ate 1 passo -1 faca
      escreval(nomes[contador])
   fimpara

Fimalgoritmo